env:
  browser: true
  es2021: true
extends:
  - airbnb
plugins:
  - prefer-arrow
parserOptions:
  ecmaVersion: latest
  sourceType: module
rules:
  react/jsx-props-no-spreading: 0
  react/prop-types: 0
  react/function-component-definition: [2, { "namedComponents": "arrow-function" }]
  prefer-arrow/prefer-arrow-functions: [
    "warn",
    {
      "disallowPrototype": true,
      "singleReturnOnly": false,
      "classPropertiesAllowed": false
    }
  ]
